version: '3'
services:
  synapse:
    image: matrixdotorg/synapse:latest
    restart: always
    volumes:
      - ./data:/data
    environment:
      SYNAPSE_SERVER_NAME: yourname.duckdns.org
      SYNAPSE_REPORT_STATS: 'yes'
    ports:
      - "8008:8008"
      - "8448:8448"
